# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' myc_proj
#'
#' Compute vector projection.
#'
#' @param u NumericVector
#' @param a NumericVector
myc_proj <- function(u, a) {
    .Call(`_myc_myc_proj`, u, a)
}

#' myc_matmult
#'
#' Matrix Multiplication
#'
#' @param A NumericMatrix
#' @param B NumericMatrix
myc_matmult <- function(A, B) {
    .Call(`_myc_myc_matmult`, A, B)
}

#' myc_diag
#'
#' Compute vector projection.
#'
#' @param A NumericMatrix
myc_diag <- function(A) {
    .Call(`_myc_myc_diag`, A)
}

#' myc_qr
#'
#' Compute QR Factorization
#'
#' @param A NumericMatrix
myc_qr <- function(A) {
    .Call(`_myc_myc_qr`, A)
}

#' myc_eigen
#'
#' Compute Eigen
#'
#' @param A NumericMatrix
myc_eigen <- function(A, margin = 1e-20) {
    .Call(`_myc_myc_eigen`, A, margin)
}

#' myc_svd
#'
#' Compute SVD
#'
#' @param A NumericMatrix
myc_svd <- function(A, margin = 1e-20) {
    .Call(`_myc_myc_svd`, A, margin)
}

#' myc_dist
#'
#' Compute Distance
#'
#' @param A NumericMatrix
myc_dist <- function(A) {
    .Call(`_myc_myc_dist`, A)
}

rcpp_hello_world <- function() {
    .Call(`_myc_rcpp_hello_world`)
}

